var POSITION_OFFSET = 0.05; // 5 cm

export const NONE = 'NONE';
export const LOADING = 'LOADING';
export const LOAD_ERROR = 'ERROR';
export const LOADED = 'LOADED';

/**
 * Data model for 3D Objects provided as input to ModelItemRenderer. The schema is as follows:
 * name - string key used to identify / retreive this model from this model array
 * selected - Is this model currently selected by the user. Used in identifying which model to execute action from Context Menu (example - remove action)
 * loading - initial loading state. Can toggle to LOADING, LOADED, ERROR when user tries to add the model to the system
 * icon_img - the icon that will be shown on the listview at the bottom for this model
 * obj - path for VRX format obj for this model checked in locally
 * materials - materials used in the VRX model (Currently unused since moving to VRX format)
 * animation - VRX skeletal animations that are baked in to the model definition itself
 * scale - initial scale of the model
 * position - initial position of the model. Primarily used to configure how close to the ground this model should be rendered (cloud rendered higher, pumpkin renderer lower)
 * type - VRX / OBJ format
 * physics - props for physics body of the model
 * shadow_width - width of the shadow plane to be configured depending on size of the model
 * shadow_height - height of the shadow plane to be configured depending on size of the model
 * spotlight_position_y - height above the object, where the spotlight should be placed at. Different for each model depending on size of the model
 * lighting_model - lighting model for this object
 * resources - all the materials (textures) used in this object, that are checked in locally.
 */
var ModelItems = [
	{
		name: 'dragon_anim',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/dragon.png'),
		obj: require('./assets/res/object_dragon_anim/object_dragon_pbr_anim.vrx'),
		materials: null,
		animation: { name: '01', delay: 0, loop: true, run: true },
		scale: [0.2, 0.2, 0.2],
		position: [0, 0, -5],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		shadow_width: 10.5,
		shadow_height: 10.5,
		spotlight_position_y: 19,
		lighting_mode: 'IBL',
		resources: [
			require('./assets/res/object_dragon_anim/object_dragon_pbr_Base_Color.png'),
			require('./assets/res/object_dragon_anim/object_dragon_pbr_Metallic.png'),
			require('./assets/res/object_dragon_anim/object_dragon_pbr_Mixed_AO.png'),
			require('./assets/res/object_dragon_anim/object_dragon_pbr_Normal_OpenGL.png'),
			require('./assets/res/object_dragon_anim/object_dragon_pbr_Roughness.png'),
		],
	},
	{
		name: 'icecream_man',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/icon_icecreamman.png'),
		obj: require('./assets/res/icecreamman_anim/icecreamman_anim_pbr.vrx'),
		materials: null,
		animation: { name: '02', delay: 0, loop: true, run: true },
		// scale: [0.3, 0.3, 0.3],
		// position: [0, 0, 0],
		scale: [0.2, 0.2, 0.2],
		position: [0, 0, -5],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		shadow_width: 3.5,
		shadow_height: 3,
		spotlight_position_y: 9.2,
		lighting_mode: 'IBL',
		resources: [
			require('./assets/res/icecreamman_anim/icecream_man_pbr_Base_Color.png'),
			require('./assets/res/icecreamman_anim/icecream_man_pbr_Metallic.png'),
			require('./assets/res/icecreamman_anim/icecream_man_pbr_Mixed_AO.png'),
			require('./assets/res/icecreamman_anim/icecream_man_pbr_Normal_OpenGL.png'),
			require('./assets/res/icecreamman_anim/icecream_man_pbr_Roughness.png'),
		],
	},
	{
		name: 'pumpkin_man',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/icon_pumpkinman.png'),
		obj: require('./assets/res/pumpkinman_anim/pumpkinman_anim.vrx'),
		materials: null,
		animation: { name: '02', delay: 0, loop: true, run: true },
		// scale: [0.3, 0.3, 0.3],
		// position: [0, 0, -1.2],
		scale: [0.2, 0.2, 0.2],
		position: [0, 0, -2],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		shadow_width: 2,
		shadow_height: 4.5,
		spotlight_position_y: 8.2,
		shadowfarz: 7.3,
		resources: [
			require('./assets/res/pumpkinman_anim/pumpkinman_body_diffuse.png'),
			require('./assets/res/pumpkinman_anim/pumpkinman_body_normal.png'),
			require('./assets/res/pumpkinman_anim/pumpkinman_body_specular.png'),
			require('./assets/res/pumpkinman_anim/pumpkinman_head_diffuse.png'),
			require('./assets/res/pumpkinman_anim/pumpkinman_head_normal.png'),
			require('./assets/res/pumpkinman_anim/pumpkinman_head_specular.png'),
		],
	},
	{
		name: 'turkeyman_anim',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/icon_turkeyman.png'),
		obj: require('./assets/res/turkeyman_anim/turkeyman_anim.vrx'),
		materials: null,
		animation: { name: '02', delay: 0, loop: true, run: true },
		scale: [0.3, 0.3, 0.3],
		position: [-0.1, 0, 0],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		shadow_width: 8,
		shadow_height: 3,
		spotlight_position_y: 9.2,
		shadowfarz: 12.3,
		resources: [
			require('./assets/res/turkeyman_anim/turkeyman_diffuse.jpg'),
			require('./assets/res/turkeyman_anim/turkeyman_normal.jpg'),
			require('./assets/res/turkeyman_anim/turkeyman_specular.jpg'),
		],
	},
	{
		name: 'pug_animated',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/icon_pug.png'),
		obj: require('./assets/res/object_pug_animated/pug_animated.vrx'),
		materials: null,
		animation: { name: 'Take 001', delay: 0, loop: true, run: true },
		scale: [0.3, 0.3, 0.3],
		position: [0, 0, 0],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		spotlight_position_y: 15.2,
		lighting_mode: 'IBL',
		resources: [
			require('./assets/res/object_pug_animated/pug_body_diffuse.png'),
			require('./assets/res/object_pug_animated/pug_body_normal.png'),
			require('./assets/res/object_pug_animated/pug_body_specular.png'),
		],
	},
	{
		name: 'emoji_smile',
		selected: false,
		loading: NONE,
		icon_img: require('./assets/res/icon_emoji_happy.png'),
		obj: require('./assets/res/emoji_smile_anim_a/emoji_smile_anim_a.vrx'),
		materials: null,
		animation: { name: '02', delay: 0, loop: true, run: true },
		scale: [0.2, 0.2, 0.2],
		position: [0, 0.497823 + POSITION_OFFSET, 0],
		type: 'VRX',
		physics: undefined,
		ref_pointer: undefined,
		resources: [
			require('./assets/res/emoji_smile_anim_a/emoji_smile_diffuse.png'),
			require('./assets/res/emoji_smile_anim_a/emoji_smile_normal.png'),
			require('./assets/res/emoji_smile_anim_a/emoji_smile_specular.png'),
		],
	},
	// {
	// 	name: 'emoji_sad',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_sad.png'),
	// 	obj: require('./assets/res/emoji_sad_anim/emoji_sad_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.49489 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_sad_anim/emoji_sad_diffuse.png'),
	// 		require('./assets/res/emoji_sad_anim/emoji_sad_normal.png'),
	// 		require('./assets/res/emoji_sad_anim/emoji_sad_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_wow',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_wow.png'),
	// 	obj: require('./assets/res/emoji_wow_anim/emoji_wow_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.49489 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_wow_anim/emoji_wow_diffuse.png'),
	// 		require('./assets/res/emoji_wow_anim/emoji_wow_normal.png'),
	// 		require('./assets/res/emoji_wow_anim/emoji_wow_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_angry',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_angry.png'),
	// 	obj: require('./assets/res/emoji_angry_anim/emoji_angry_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.49489 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	emitter_name: 'EmojiAngryEmitter',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_angry_anim/emoji_angry_diffuse.png'),
	// 		require('./assets/res/emoji_angry_anim/emoji_angry_normal.png'),
	// 		require('./assets/res/emoji_angry_anim/emoji_angry_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_kiss',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_kiss.png'),
	// 	obj: require('./assets/res/emoji_kiss_anim/emoji_kiss_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.49489 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_kiss_anim/emoji_kiss_diffuse.png'),
	// 		require('./assets/res/emoji_kiss_anim/emoji_kiss_normal.png'),
	// 		require('./assets/res/emoji_kiss_anim/emoji_kiss_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_heart',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_heart.png'),
	// 	obj: require('./assets/res/emoji_heart_anim/emoji_heart_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.451719 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_heart_anim/emoji_heart.png'),
	// 		require('./assets/res/emoji_heart_anim/emoji_heart_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_thumbsup',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_thumbsup.png'),
	// 	obj: require('./assets/res/emoji_thumbsup_anim/emoji_thumbsup_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.506186 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_thumbsup_anim/emoji_thumbsup_diffuse.png'),
	// 		require('./assets/res/emoji_thumbsup_anim/emoji_thumbsup_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'emoji_poop',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_poop.png'),
	// 	obj: require('./assets/res/emoji_poop_anim/emoji_poop_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.353032 + POSITION_OFFSET, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	resources: [
	// 		require('./assets/res/emoji_poop_anim/emoji_poop_diffuse.png'),
	// 		require('./assets/res/emoji_poop_anim/emoji_poop_normal.png'),
	// 		require('./assets/res/emoji_poop_anim/emoji_poop_specular.png'),
	// 	],
	// },
	// {
	// 	name: 'object_star',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_star.png'),
	// 	obj: require('./assets/res/object_star_anim/object_star_anim_pbr.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.25, 0.25, 0.25],
	// 	position: [0, 0.939014 + POSITION_OFFSET, 0],
	// 	physics: undefined,
	// 	type: 'VRX',
	// 	ref_pointer: undefined,
	// 	lighting_mode: 'IBL',
	// 	spotlight_position_y: 9.2,

	// 	resources: [
	// 		require('./assets/res/object_star_anim/blinn1_Base_Color.png'),
	// 		require('./assets/res/object_star_anim/blinn1_Metallic.png'),
	// 		require('./assets/res/object_star_anim/blinn1_Roughness.png'),
	// 	],
	// },
	// {
	// 	name: 'object_rainbow',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_rainbow.png'),
	// 	obj: require('./assets/res/object_rainbow_anim/object_rainbow_anim.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [1, 1, 1],
	// 	position: [0, 0.235285 + POSITION_OFFSET, 0],
	// 	physics: undefined,
	// 	type: 'VRX',
	// 	ref_pointer: undefined,
	// 	lighting_mode: 'IBL',
	// 	spotlight_position_y: 9.2,

	// 	resources: [
	// 		require('./assets/res/object_rainbow_anim/object_rainbow_Base_Color.png'),
	// 		require('./assets/res/object_rainbow_anim/object_rainbow_Metallic.png'),
	// 		require('./assets/res/object_rainbow_anim/object_rainbow_Roughness.png'),
	// 	],
	// },
	// {
	// 	name: 'object_cloud',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_emoji_cloud.png'),
	// 	obj: require('./assets/res/object_cloud_anim/object_cloud_anim_pbr.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.3, 0.3, 0.3],
	// 	position: [0, 0.235285 + POSITION_OFFSET, 0],
	// 	physics: undefined,
	// 	type: 'VRX',
	// 	ref_pointer: undefined,
	// 	lighting_mode: 'IBL',
	// 	spotlight_position_y: 9.2,
	// 	resources: [
	// 		require('./assets/res/object_cloud_anim/object_cloud_anim_object_cloud_BaseColor.png'),
	// 		require('./assets/res/object_cloud_anim/object_cloud_anim_object_cloud_Metallic.png'),
	// 		require('./assets/res/object_cloud_anim/object_cloud_anim_object_cloud_Roughness.png'),
	// 	],
	// },
	// {
	// 	name: 'object_bday_cake',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_object_cake.png'),
	// 	obj: require('./assets/res/object_bday_cake/object_bday_cake_pbr.vrx'),
	// 	materials: null,
	// 	animation: null,
	// 	scale: [0.2, 0.2, 0.2],
	// 	position: [0, 0.165234, 0],
	// 	type: 'VRX',
	// 	emitter_name: 'BirthdayCakeEmitter',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	lighting_mode: 'IBL',
	// 	spotlight_position_y: 9.2,
	// 	resources: [
	// 		require('./assets/res/object_bday_cake/blinn1_Roughness.png'),
	// 		require('./assets/res/object_bday_cake/blinn1_Metallic.png'),
	// 		require('./assets/res/object_bday_cake/blinn1_Normal_OpenGL.png'),
	// 		require('./assets/res/object_bday_cake/blinn1_Base_Color.png'),
	// 	],
	// },
	// {
	// 	name: 'object_flowers',
	// 	selected: false,
	// 	loading: NONE,
	// 	icon_img: require('./assets/res/icon_object_flowers.png'),
	// 	obj: require('./assets/res/object_flowers_anim/object_flowers_anim_pbr.vrx'),
	// 	materials: null,
	// 	animation: { name: '02', delay: 0, loop: true, run: true },
	// 	scale: [0.6, 0.6, 0.6],
	// 	position: [0, 0.29076, 0],
	// 	type: 'VRX',
	// 	physics: undefined,
	// 	ref_pointer: undefined,
	// 	lighting_mode: 'IBL',
	// 	resources: [
	// 		require('./assets/res/object_flowers_anim/blinn1_Roughness.png'),
	// 		require('./assets/res/object_flowers_anim/blinn1_Metallic.png'),
	// 		require('./assets/res/object_flowers_anim/blinn1_Base_Color.png'),
	// 		require('./assets/res/object_flowers_anim/blinn1_Normal_OpenGL.png'),
	// 	],
	// },
];

module.exports = {
	getModelArray: function () {
		return ModelItems;
	},
};
